package org.apache.hadoop.hbase.mapreduce;

import java.util.Map;
import java.util.HashMap;

import org.apache.hadoop.hbase.util.Bytes;
import org.apache.hadoop.hbase.io.ImmutableBytesWritable;

class BenfordAndSon {
  public final static Map segments = new HashMap<ImmutableBytesWritable, Integer>() {
    {
      put(new ImmutableBytesWritable(Bytes.toBytes("")), 0);
      put(new ImmutableBytesWritable(Bytes.toBytes("0")), 0);
      put(new ImmutableBytesWritable(Bytes.toBytes("1")), 1);
      put(new ImmutableBytesWritable(Bytes.toBytes("2")), 2);
      put(new ImmutableBytesWritable(Bytes.toBytes("3")), 3);
      put(new ImmutableBytesWritable(Bytes.toBytes("4")), 4);
      put(new ImmutableBytesWritable(Bytes.toBytes("5")), 5);
      put(new ImmutableBytesWritable(Bytes.toBytes("6")), 6);
      put(new ImmutableBytesWritable(Bytes.toBytes("7")), 7);
      put(new ImmutableBytesWritable(Bytes.toBytes("8")), 8);
      put(new ImmutableBytesWritable(Bytes.toBytes("9")), 9);
      put(new ImmutableBytesWritable(Bytes.toBytes("00")), 0);
      put(new ImmutableBytesWritable(Bytes.toBytes("01")), 1);
      put(new ImmutableBytesWritable(Bytes.toBytes("02")), 2);
      put(new ImmutableBytesWritable(Bytes.toBytes("03")), 3);
      put(new ImmutableBytesWritable(Bytes.toBytes("04")), 4);
      put(new ImmutableBytesWritable(Bytes.toBytes("05")), 5);
      put(new ImmutableBytesWritable(Bytes.toBytes("06")), 6);
      put(new ImmutableBytesWritable(Bytes.toBytes("07")), 7);
      put(new ImmutableBytesWritable(Bytes.toBytes("08")), 8);
      put(new ImmutableBytesWritable(Bytes.toBytes("09")), 9);
      put(new ImmutableBytesWritable(Bytes.toBytes("10")), 10);
      put(new ImmutableBytesWritable(Bytes.toBytes("11")), 11);
      put(new ImmutableBytesWritable(Bytes.toBytes("12")), 12);
      put(new ImmutableBytesWritable(Bytes.toBytes("13")), 13);
      put(new ImmutableBytesWritable(Bytes.toBytes("14")), 14);
      put(new ImmutableBytesWritable(Bytes.toBytes("15")), 15);
      put(new ImmutableBytesWritable(Bytes.toBytes("16")), 16);
      put(new ImmutableBytesWritable(Bytes.toBytes("17")), 17);
      put(new ImmutableBytesWritable(Bytes.toBytes("18")), 18);
      put(new ImmutableBytesWritable(Bytes.toBytes("19")), 19);
      put(new ImmutableBytesWritable(Bytes.toBytes("20")), 20);
      put(new ImmutableBytesWritable(Bytes.toBytes("21")), 21);
      put(new ImmutableBytesWritable(Bytes.toBytes("22")), 22);
      put(new ImmutableBytesWritable(Bytes.toBytes("23")), 23);
      put(new ImmutableBytesWritable(Bytes.toBytes("24")), 24);
      put(new ImmutableBytesWritable(Bytes.toBytes("25")), 25);
      put(new ImmutableBytesWritable(Bytes.toBytes("26")), 26);
      put(new ImmutableBytesWritable(Bytes.toBytes("27")), 27);
      put(new ImmutableBytesWritable(Bytes.toBytes("28")), 28);
      put(new ImmutableBytesWritable(Bytes.toBytes("29")), 29);
      put(new ImmutableBytesWritable(Bytes.toBytes("30")), 30);
      put(new ImmutableBytesWritable(Bytes.toBytes("31")), 31);
      put(new ImmutableBytesWritable(Bytes.toBytes("32")), 32);
      put(new ImmutableBytesWritable(Bytes.toBytes("33")), 33);
      put(new ImmutableBytesWritable(Bytes.toBytes("34")), 34);
      put(new ImmutableBytesWritable(Bytes.toBytes("35")), 35);
      put(new ImmutableBytesWritable(Bytes.toBytes("36")), 36);
      put(new ImmutableBytesWritable(Bytes.toBytes("37")), 37);
      put(new ImmutableBytesWritable(Bytes.toBytes("38")), 38);
      put(new ImmutableBytesWritable(Bytes.toBytes("39")), 39);
      put(new ImmutableBytesWritable(Bytes.toBytes("40")), 40);
      put(new ImmutableBytesWritable(Bytes.toBytes("41")), 41);
      put(new ImmutableBytesWritable(Bytes.toBytes("42")), 42);
      put(new ImmutableBytesWritable(Bytes.toBytes("43")), 43);
      put(new ImmutableBytesWritable(Bytes.toBytes("44")), 44);
      put(new ImmutableBytesWritable(Bytes.toBytes("45")), 45);
      put(new ImmutableBytesWritable(Bytes.toBytes("46")), 46);
      put(new ImmutableBytesWritable(Bytes.toBytes("47")), 47);
      put(new ImmutableBytesWritable(Bytes.toBytes("48")), 48);
      put(new ImmutableBytesWritable(Bytes.toBytes("49")), 49);
      put(new ImmutableBytesWritable(Bytes.toBytes("50")), 50);
      put(new ImmutableBytesWritable(Bytes.toBytes("51")), 51);
      put(new ImmutableBytesWritable(Bytes.toBytes("52")), 52);
      put(new ImmutableBytesWritable(Bytes.toBytes("53")), 53);
      put(new ImmutableBytesWritable(Bytes.toBytes("54")), 54);
      put(new ImmutableBytesWritable(Bytes.toBytes("55")), 55);
      put(new ImmutableBytesWritable(Bytes.toBytes("56")), 56);
      put(new ImmutableBytesWritable(Bytes.toBytes("57")), 57);
      put(new ImmutableBytesWritable(Bytes.toBytes("58")), 58);
      put(new ImmutableBytesWritable(Bytes.toBytes("59")), 59);
      put(new ImmutableBytesWritable(Bytes.toBytes("60")), 60);
      put(new ImmutableBytesWritable(Bytes.toBytes("61")), 61);
      put(new ImmutableBytesWritable(Bytes.toBytes("62")), 62);
      put(new ImmutableBytesWritable(Bytes.toBytes("63")), 63);
      put(new ImmutableBytesWritable(Bytes.toBytes("64")), 64);
      put(new ImmutableBytesWritable(Bytes.toBytes("65")), 65);
      put(new ImmutableBytesWritable(Bytes.toBytes("66")), 66);
      put(new ImmutableBytesWritable(Bytes.toBytes("67")), 67);
      put(new ImmutableBytesWritable(Bytes.toBytes("68")), 68);
      put(new ImmutableBytesWritable(Bytes.toBytes("69")), 69);
      put(new ImmutableBytesWritable(Bytes.toBytes("70")), 70);
      put(new ImmutableBytesWritable(Bytes.toBytes("71")), 71);
      put(new ImmutableBytesWritable(Bytes.toBytes("72")), 72);
      put(new ImmutableBytesWritable(Bytes.toBytes("73")), 73);
      put(new ImmutableBytesWritable(Bytes.toBytes("74")), 74);
      put(new ImmutableBytesWritable(Bytes.toBytes("75")), 75);
      put(new ImmutableBytesWritable(Bytes.toBytes("76")), 76);
      put(new ImmutableBytesWritable(Bytes.toBytes("77")), 77);
      put(new ImmutableBytesWritable(Bytes.toBytes("78")), 78);
      put(new ImmutableBytesWritable(Bytes.toBytes("79")), 79);
      put(new ImmutableBytesWritable(Bytes.toBytes("80")), 80);
      put(new ImmutableBytesWritable(Bytes.toBytes("81")), 81);
      put(new ImmutableBytesWritable(Bytes.toBytes("82")), 82);
      put(new ImmutableBytesWritable(Bytes.toBytes("83")), 83);
      put(new ImmutableBytesWritable(Bytes.toBytes("84")), 84);
      put(new ImmutableBytesWritable(Bytes.toBytes("85")), 85);
      put(new ImmutableBytesWritable(Bytes.toBytes("86")), 86);
      put(new ImmutableBytesWritable(Bytes.toBytes("87")), 87);
      put(new ImmutableBytesWritable(Bytes.toBytes("88")), 88);
      put(new ImmutableBytesWritable(Bytes.toBytes("89")), 89);
      put(new ImmutableBytesWritable(Bytes.toBytes("90")), 90);
      put(new ImmutableBytesWritable(Bytes.toBytes("91")), 91);
      put(new ImmutableBytesWritable(Bytes.toBytes("92")), 92);
      put(new ImmutableBytesWritable(Bytes.toBytes("93")), 93);
      put(new ImmutableBytesWritable(Bytes.toBytes("94")), 94);
      put(new ImmutableBytesWritable(Bytes.toBytes("95")), 95);
      put(new ImmutableBytesWritable(Bytes.toBytes("96")), 96);
      put(new ImmutableBytesWritable(Bytes.toBytes("97")), 97);
      put(new ImmutableBytesWritable(Bytes.toBytes("98")), 98);
      put(new ImmutableBytesWritable(Bytes.toBytes("99")), 99);
    }
  };
}
